sylius_grid:
    grids:
        setono_sylius_out_of_office_period:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_out_of_office.model.out_of_office_period.class%"
            sorting:
                startsAt: desc
            fields:
                name:
                    type: string
                    label: setono_sylius_out_of_office.ui.name
                    sortable: ~
                channels:
                    type: twig
                    label: setono_sylius_out_of_office.ui.channels
                    options:
                        template: "@SetonoSyliusOutOfOfficePlugin/admin/grid/field/channels.html.twig"
                active:
                    type: twig
                    label: setono_sylius_out_of_office.ui.active_now
                    path: .
                    options:
                        template: "@SetonoSyliusOutOfOfficePlugin/admin/grid/field/active.html.twig"
                startsAt:
                    type: datetime
                    label: setono_sylius_out_of_office.ui.starts_at
                    sortable: ~
                endsAt:
                    type: datetime
                    label: setono_sylius_out_of_office.ui.ends_at
                    sortable: ~
                enabled:
                    type: twig
                    label: setono_sylius_out_of_office.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                name:
                    type: string
                    label: setono_sylius_out_of_office.ui.name
                    options:
                        fields: [name]
                enabled:
                    type: boolean
                    label: setono_sylius_out_of_office.ui.enabled
                channel:
                    type: entity
                    label: setono_sylius_out_of_office.ui.channel
                    options:
                        fields: [channels]
                    form_options:
                        class: "%sylius.model.channel.class%"
                        multiple: true
                        choice_label: name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
